// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzMgDpriX5holFgJYbKY50_o4OtvylIQs',
    appId: '1:958969720670:web:559cb0d4874a6b702829cf',
    messagingSenderId: '958969720670',
    projectId: 'bmi-flutter-85227',
    authDomain: 'bmi-flutter-85227.firebaseapp.com',
    storageBucket: 'bmi-flutter-85227.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnPAd8aGC-U3RtA2P-pWP3TtHJcqWklNo',
    appId: '1:958969720670:android:8d9ee5944b67861d2829cf',
    messagingSenderId: '958969720670',
    projectId: 'bmi-flutter-85227',
    storageBucket: 'bmi-flutter-85227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx1YIiMgMfLYGCqYdi2T0U1HDPX_W2NY4',
    appId: '1:958969720670:ios:a197130453202c2c2829cf',
    messagingSenderId: '958969720670',
    projectId: 'bmi-flutter-85227',
    storageBucket: 'bmi-flutter-85227.appspot.com',
    iosClientId: '958969720670-9lrp301dcbl8r72imvag0stu75cpkass.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx1YIiMgMfLYGCqYdi2T0U1HDPX_W2NY4',
    appId: '1:958969720670:ios:a197130453202c2c2829cf',
    messagingSenderId: '958969720670',
    projectId: 'bmi-flutter-85227',
    storageBucket: 'bmi-flutter-85227.appspot.com',
    iosClientId: '958969720670-9lrp301dcbl8r72imvag0stu75cpkass.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiCheck',
  );
}
